inputs:
  version:
    description: "A version to install ecschedule"
    default: "v0.3.1"
runs:
  using: "composite"
  steps:
    - run: |
        DIRNAME=ecschedule_${{ inputs.version }}_linux_amd64
        cd /tmp
        curl -sLO https://github.com/Songmu/ecschedule/releases/download/${{ inputs.version }}/${DIRNAME}.tar.gz
        tar zxvf ${DIRNAME}.tar.gz
        sudo mv ${DIRNAME}/ecschedule /usr/local/bin/ecschedule
        rm -rf ${DIRNAME} ${DIRNAME}.zip
      shell: bash
