name: test
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        go-version: [1.12.x, 1.13.x]
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: lint
      run: |
        GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
        bin/golint -set_exit_status ./...
      if: "matrix.os == 'ubuntu-latest'"
    - name: test
      run: |
        go test -coverprofile coverage.out ./...
    - name: prepare-coverage
      run: |
        GO111MODULE=off GOBIN=$(pwd)/bin go get github.com/ricallinson/covfmt
        mkdir coverage
        cat coverage.out | bin/covfmt > ./coverage/lcov.info
      if: "github.event_name == 'push' && matrix.os == 'ubuntu-latest' && matrix.go-version == '1.13.x'"
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
      if: "github.event_name == 'push' && matrix.os == 'ubuntu-latest' && matrix.go-version == '1.13.x'"
